version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 6%bFFZ8'S@3B^Hg
      MYSQL_ROOT_PASSWORD: fB3ybY_&9CurGpn
    ports:
      - '3306:3306'
    volumes:
      - mysql-database:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.7'
        NODE_MAJOR: '14'
        YARN_VERSION: '1.22.5'
    command: bash -c "rm -f tmp/pid/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    tmpfs:
      - /tmp
volumes:
  mysql-database:
    driver: local
